# Generated by Django 3.1.7 on 2021-12-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211213_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionitem',
            old_name='ueser',
            new_name='user',
        ),
    ]
