# Generated by Django 3.1.7 on 2021-12-13 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211213_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='bid_winner',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='max_bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.FloatField(null=True)),
                ('auction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.auctionitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
